version: '3.8'

services:

  database:
    image: postgres:15.4
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CollStat
      POSTGREST_DB: postgres
    volumes:
       - /mnt/efs/fs1/.db_data:/var/lib/postgresql/data/
       - /tmp/:/tmp/
         # - ./.db_data:/var/lib/postgresql/data/
