version: '3.7'

services:
  postgres:
    container_name: FLDB
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: FLVoteData 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LotsOfData
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - /Users/johnlarus/tmp:/mnt/tmp

#  pgadmin:
#    image: dpage/pgadmin4:8.6
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
#      PGADMIN_DEFAULT_PASSWORD: LotsOfData
#      PGADMIN_LISTEN_PORT: 80
#    ports:
#      - 15432:80
#    volumes:
#      - postgres_volume:/var/lib/pgadmin
#    depends_on:
#      - postgres

volumes:
  postgres_volume:
    external: true 

